services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playground-golang-app
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
        - action: rebuild
          path: ./main.go
    environment:
      - GIN_MODE=debug
