services:
  postgres:
    container_name: playground-postgres
    image: postgres:15.5-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  redis:
    container_name: playground-redis
    image: redis:7.2.4-alpine
    ports:
      - ${REDIS_PORT}:6379
    restart: always
