name: auto approve
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    types:
      - opened
defaults:
  run:
    shell: bash
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.actor }} == '@otakakot'
    steps:
      - name: Check branch
        run: echo "${{ github.head_ref }}"
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        with:
          app-id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Approve
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh pr review --approve "${PR_URL}"
